// 文案資料：每個 sheet 對應網站一個區域，每筆 row 對應一段文字
// Row 欄位順序：[位置, KEY, 類型, 目前文案, 備註]
// （生成時會在最後加一欄空白「修改後」給委託人填）

module.exports = {
  intro: {
    title: '使用說明',
    rows: [
      ['請在「修改後」欄位填寫新文案。留空＝不變。'],
      ['「KEY」是系統識別碼，請勿改動，工程師會用它把您的修改同步回網站。'],
      ['若文案中有花括號 {變數名}（例：{姓名}、{報名序號}），請保留不要刪除，這是系統自動帶入的學員資料。'],
      ['每個 sheet 底部有「新增項目」區，您可寫下「想再加什麼字」「希望某段改成怎樣」的需求。'],
      ['寄回給工程師後，會依您的修改更新網站，再請您驗證。'],
      [''],
      ['每個 sheet 的欄位說明：'],
      ['位置 = 在網站哪一區（例：報名表 > Q5）'],
      ['KEY = 識別碼（請勿動）'],
      ['類型 = 文字種類（標題／按鈕／說明等）'],
      ['目前文案 = 現在網站上的文字'],
      ['修改後 = 您要改的文字（淺色底色那欄）'],
      ['備註 = 工程師補充說明（變數提示等）'],
    ],
  },

  sheets: [
    // ============== 首頁 ==============
    {
      key: 'home',
      title: '首頁',
      rows: [
        // Header / Nav
        ['首頁 > 導覽', 'home.nav.about', '連結', '活動緣起', ''],
        ['首頁 > 導覽', 'home.nav.teachers', '連結', '師資', ''],
        ['首頁 > 導覽', 'home.nav.faq', '連結', '常見問題', ''],
        ['首頁 > 導覽', 'home.nav.register', '連結', '立即報名', ''],
        ['首頁 > 導覽', 'home.nav.member', '連結', '查詢報名狀態｜學員專區', ''],
        // Hero
        ['首頁 > Hero', 'home.hero.eyebrow', '段落', '第二屆・台灣四念處禪修之旅 · 2026', ''],
        ['首頁 > Hero', 'home.hero.title', '主標', '唯一路', ''],
        ['首頁 > Hero', 'home.hero.subtitle', '副標', '解脫', ''],
        ['首頁 > Hero', 'home.hero.subtitle.context', '段落', '「解脫」從如實知開始', ''],
        ['首頁 > Hero', 'home.hero.date', '段落', '日期：8/20 — 24（五天）', ''],
        ['首頁 > Hero', 'home.hero.location', '段落', '地點：南投・日月潭', ''],
        ['首頁 > Hero', 'home.hero.regperiod', '段落', '報名期間：2026/05/11 — 05/25', ''],
        ['首頁 > Hero', 'home.hero.lead', '段落', '大夢醒時，「看見」，正是解脫的起點。在念頭的夢境中迷失已久，是時候回過頭來，如實觀照生命的真相。', ''],
        ['首頁 > Hero', 'home.hero.quote', '引言', '今日就啟程，趕在時間的流沙覆蓋佛陀的足跡之前。勿要蹉跎，直至那天，再次淪落於遙遙無期的流離失所與茫然無依。', ''],
        ['首頁 > Hero', 'home.hero.quote.author', '署名', '隆波帕默尊者', ''],
        ['首頁 > Hero', 'home.hero.cta1', '按鈕', '立即報名 →', ''],
        ['首頁 > Hero', 'home.hero.cta2', '按鈕', '查詢報名狀態｜學員專區 →', ''],
        // About
        ['首頁 > 活動緣起', 'home.about.title', '標題', '唯一路', ''],
        ['首頁 > 活動緣起', 'home.about.desc1', '段落', '承蒙隆波帕默尊者慈悲指定，由助教老師團隊親自指導。本次禪修將於 2026 年 8 月 20 日至 24 日於南投日月潭湖畔會館展開，為期五日四夜。', ''],
        ['首頁 > 活動緣起', 'home.about.desc2', '段落', '誠摯邀請您，走入日月潭的山水之間，在助教老師們的引導下，親自踏上四念處的覺醒之路。修行，就從此時此刻的「看見」開始。', ''],
        ['首頁 > 活動緣起', 'home.about.quote', '引言', '大夢醒時，「看見」，正是解脫的起點。在念頭的夢境中迷失已久，是時候回過頭來，如實觀照生命的真相。', ''],
        // At a glance
        ['首頁 > 活動資訊', 'home.at_glance.title', '標題', '活動資訊', ''],
        ['首頁 > 活動資訊', 'home.at_glance.date_value', '段落', '08.20—24', ''],
        ['首頁 > 活動資訊', 'home.at_glance.date_detail', '段落', '2026 · 共五日', ''],
        ['首頁 > 活動資訊', 'home.at_glance.venue_value', '段落', '南投・日月潭', ''],
        ['首頁 > 活動資訊', 'home.at_glance.host_value', '段落', '四念處禪修學會', ''],
        ['首頁 > 活動資訊', 'home.at_glance.capacity_value', '段落', '250', ''],
        ['首頁 > 活動資訊', 'home.at_glance.capacity_note', '段落', '名額有限，額滿為止', ''],
        // Teachers
        ['首頁 > 師資', 'home.teachers.title', '標題', '指導老師團隊', ''],
        ['首頁 > 師資', 'home.teachers.desc', '段落', '承蒙隆波帕默尊者慈悲教導，由弟子助教老師團隊親臨授課。', ''],
        ['首頁 > 師資', 'home.teachers.online_title', '小標', '泰國連線授課', ''],
        ['首頁 > 師資', 'home.teachers.inperson_title', '小標', '親臨授課', ''],
        // Timeline
        ['首頁 > 重要時程', 'home.timeline.title', '標題', '重要時程', ''],
        ['首頁 > 重要時程', 'home.timeline.desc', '段落', '請留意以下關鍵日期。', ''],
        ['首頁 > 重要時程 > 1', 'home.timeline.item1.date', '日期', '05.11 — 05.25', ''],
        ['首頁 > 重要時程 > 1', 'home.timeline.item1.title', '小標', '報名期間', ''],
        ['首頁 > 重要時程 > 1', 'home.timeline.item1.desc', '段落', '線上填寫報名表，提交個人資料與修學背景。', ''],
        ['首頁 > 重要時程 > 2', 'home.timeline.item2.date', '日期', '06.06　錄取通知', ''],
        ['首頁 > 重要時程 > 2', 'home.timeline.item2.title', '小標', '錄取通知發送', ''],
        ['首頁 > 重要時程 > 2', 'home.timeline.item2.desc', '段落', '錄取者將於 6 月 6 日收到 E-mail 通知。提交報名表單不代表已錄取。', ''],
        ['首頁 > 重要時程 > 3', 'home.timeline.item3.date', '日期', '06.15　繳費截止', ''],
        ['首頁 > 重要時程 > 3', 'home.timeline.item3.title', '小標', '完成繳費以正式錄取', ''],
        ['首頁 > 重要時程 > 3', 'home.timeline.item3.desc', '段落', '錄取者須於 6 月 15 日台北時間晚上 8 時前完成繳費，才算正式錄取。', ''],
        ['首頁 > 重要時程 > 4', 'home.timeline.item4.date', '日期', '08.20 — 08.24', ''],
        ['首頁 > 重要時程 > 4', 'home.timeline.item4.title', '小標', '禪修正式開始', ''],
        ['首頁 > 重要時程 > 4', 'home.timeline.item4.desc', '段落', '報到、安單、開始為期五日四夜的四念處禪修。', ''],
        // FAQ
        ['首頁 > FAQ', 'home.faq.title', '標題', '常見問題', ''],
        ['首頁 > FAQ > Q1', 'home.faq.q1.title', '題目', '需要具備什麼條件才能報名？', ''],
        ['首頁 > FAQ > Q1', 'home.faq.q1.cond1.label', '說明', '聞法條件（任一即可）', ''],
        ['首頁 > FAQ > Q1', 'home.faq.q1.cond1.opt1', '說明', '曾參加過任意一屆隆波帕默尊者體系的線下實體或線上網路課程', ''],
        ['首頁 > FAQ > Q1', 'home.faq.q1.cond1.opt2', '說明', '參加過每月 ZOOM 指導老師線上互動', ''],
        ['首頁 > FAQ > Q1', 'home.faq.q1.cond1.opt3', '說明', '完整觀看 3 屆泰國禪修之旅課程錄影', ''],
        ['首頁 > FAQ > Q1', 'home.faq.q1.cond1.opt4', '說明', '聆聽隆波帕默尊者法談開示 30 篇以上', ''],
        ['首頁 > FAQ > Q1', 'home.faq.q1.cond2', '說明', '持守五戒', ''],
        ['首頁 > FAQ > Q1', 'home.faq.q1.cond3', '說明', '堅持做固定形式的練習', ''],
        ['首頁 > FAQ > Q2', 'home.faq.q2.title', '題目', '錄取流程是怎樣的？', ''],
        ['首頁 > FAQ > Q2', 'home.faq.q2.desc1', '說明', '提交報名表單不代表已錄取。錄取通知將於 6 月 6 日以 Email 發送，請留意收件匣與垃圾信箱。', ''],
        ['首頁 > FAQ > Q2', 'home.faq.q2.desc2', '說明', '收到錄取通知後，須於 6 月 15 日台北時間晚上 8 時前匯款／刷卡繳交食宿、場地及交通等費用，並至學員專區填寫繳費資料，才算完成正式錄取。', ''],
        ['首頁 > FAQ > Q2', 'home.faq.q2.desc3', '說明', '正式錄取者將建立 LINE 及微信群組聯繫。請勿在錄取確認前購買機票或安排行程。', ''],
        ['首頁 > FAQ > Q3', 'home.faq.q3.title', '題目', '禪修期間需要全程禁語嗎？', ''],
        ['首頁 > FAQ > Q3', 'home.faq.q3.answer', '說明', '是的，禪修期間全程禁語（除與助教老師小參時間外），這是維持禪修品質的重要規範。', ''],
        ['首頁 > FAQ > Q4', 'home.faq.q4.title', '題目', '住宿安排是怎樣的？', ''],
        ['首頁 > FAQ > Q4', 'home.faq.q4.answer', '說明', '於日月潭湖畔會館，提供雙人房、多人房等多種房型，含床具、棉被、毛巾等基本備品。詳細房型與費用於錄取後通知，並由學員專區完成登記。', ''],
        ['首頁 > FAQ > Q5', 'home.faq.q5.title', '題目', '飲食有什麼安排？', ''],
        ['首頁 > FAQ > Q5', 'home.faq.q5.answer', '說明', '每日提供早、午二餐素食，過午不食。飲食以清淡為主，禁五辛、酒類。如有特殊飲食需求（過敏、無麩質等），請於食宿登記時註明。', ''],
        ['首頁 > FAQ > Q6', 'home.faq.q6.title', '題目', '交通如何前往？', ''],
        ['首頁 > FAQ > Q6', 'home.faq.q6.answer', '說明', '可自行前往日月潭禪修場地，亦可選擇主辦單位之台中／台北接駁服務。詳細路線、接駁集合時間與費用於錄取後於學員專區提供。', ''],
        ['首頁 > FAQ > Q7', 'home.faq.q7.title', '題目', '費用大約多少？', ''],
        ['首頁 > FAQ > Q7', 'home.faq.q7.answer', '說明', '禪修課程本身免費。食宿、場地及交通等費用依房型由參加者自理，具體金額會在錄取通知中載明，並由學員專區完成登記繳費。', ''],
        ['首頁 > FAQ > Q8', 'home.faq.q8.title', '題目', '需要自備什麼物品？', ''],
        ['首頁 > FAQ > Q8', 'home.faq.q8.answer', '說明', '建議準備寬鬆舒適的禪修服、個人盥洗用品、保暖衣物等。詳細打包清單會於錄取後一併提供。', ''],
        // Footer
        ['首頁 > Footer', 'home.footer.about', '段落', '護持佛法四念處，推廣隆波帕默尊者教導的禪修法門，邀請大眾一起踏上覺醒之路。', ''],
        ['首頁 > Footer', 'home.footer.tagline', '段落', '唯一路 · 從如實知開始', ''],
      ],
    },

    // ============== 報名表 ==============
    {
      key: 'register',
      title: '報名表',
      rows: [
        ['報名表 > 頁首', 'register.page.title', '標題', '第二屆台灣四念處禪修・課程報名', ''],
        ['報名表 > 頁首', 'register.page.subtitle', '副標', '報名期間：2026/05/11 上午 10:00 — 2026/05/25 晚上 24:00（台北時間）', ''],
        ['報名表 > 頁首', 'register.page.subtitle2', '副標', '提交報名表單不代表已錄取，錄取結果將於 6/6 以 Email 通知。', ''],
        ['報名表 > 關閉狀態', 'register.closed.title.notyet', '標題', '報名尚未開放', ''],
        ['報名表 > 關閉狀態', 'register.closed.title.past', '標題', '報名已截止', ''],
        ['報名表 > 關閉狀態', 'register.closed.desc.notyet', '說明', '報名將於 2026/05/11 上午 10 點（台北時間）開放。感謝您的關注，請屆時再回到本頁。', ''],
        ['報名表 > 關閉狀態', 'register.closed.desc.past', '說明', '報名期間已於 2026/05/25 晚上 24 點（台北時間）截止。如有疑問請聯繫學會。', ''],
        // Step 1
        ['報名表 > Step1', 'register.step1.title', '標題', '課程資訊', ''],
        ['報名表 > Step1', 'register.step1.desc', '說明', '請仔細閱讀課程基本資訊，確認後進入下一步。', ''],
        ['報名表 > Step1 > 課程資訊', 'register.step1.time_value', '段落', '2026/08/20 ～ 08/24（共 5 天）', ''],
        ['報名表 > Step1 > 課程資訊', 'register.step1.method_value', '段落', '實體禪修', ''],
        ['報名表 > Step1 > 課程資訊', 'register.step1.location_value', '段落', '南投・日月潭湖畔會館', ''],
        ['報名表 > Step1 > 課程資訊', 'register.step1.capacity_value', '段落', '250 名（額滿為止）', ''],
        ['報名表 > Step1 > 課程資訊', 'register.step1.fee_value', '段落', '課程免費，食宿、場地及交通等費用自理（NT$18,600）', ''],
        ['報名表 > Step1 > 傳承', 'register.step1.section2_desc', '段落', '承蒙隆波帕默尊者慈悲指定，由助教老師團隊親自指導。', ''],
        ['報名表 > Step1 > 老師', 'register.step1.teacher1', '段落', '阿姜納 Ajahn Nat Sriwachirawat', ''],
        ['報名表 > Step1 > 老師', 'register.step1.teacher2', '段落', '阿姜巴山 Ajahn Prasan Bhuddhakulsomsiri', ''],
        ['報名表 > Step1 > 老師', 'register.step1.teacher3', '段落', '阿姜妮 Ajahn Nitiya Petchpaiboon', ''],
        ['報名表 > Step1 > 老師', 'register.step1.teacher4', '段落', '阿姜松 Ajahn Napatpol Kunatanasate', ''],
        // Step 2
        ['報名表 > Step2', 'register.step2.title', '標題', '報名資格', ''],
        ['報名表 > Step2', 'register.step2.desc', '說明', '請確認您符合以下資格後再進入下一步。', ''],
        ['報名表 > Step2 > 條件', 'register.step2.section1_title', '小標', '報名條件（須同時滿足三條件）', ''],
        ['報名表 > Step2 > 條件1', 'register.step2.cond1.title', '小標', '1. 聞法條件（任一即可）', ''],
        ['報名表 > Step2 > 條件1', 'register.step2.cond1.opt1', '說明', '曾參加過任意一屆隆波帕默尊者體系的線下實體或線上網路課程', ''],
        ['報名表 > Step2 > 條件1', 'register.step2.cond1.opt2', '說明', '參加過每月 ZOOM 指導老師線上互動', ''],
        ['報名表 > Step2 > 條件1', 'register.step2.cond1.opt3', '說明', '完整觀看／聆聽過 3 屆泰國禪修之旅課程錄影／錄音', ''],
        ['報名表 > Step2 > 條件1', 'register.step2.cond1.opt4', '說明', '觀看／聆聽隆波帕默尊者法談開示 30 篇以上', ''],
        ['報名表 > Step2 > 條件2', 'register.step2.cond2.title', '小標', '2. 持守五戒', ''],
        ['報名表 > Step2 > 條件3', 'register.step2.cond3.title', '小標', '3. 堅持做固定形式的練習（如：經行、靜坐⋯）', ''],
        ['報名表 > Step2 > 流程', 'register.step2.process1', '說明', '1. 提交報名表後，將於 6 月 6 日以 Email 發送錄取通知（提交報名表單不代表已錄取）。', ''],
        ['報名表 > Step2 > 流程', 'register.step2.process2', '說明', '2. 收到錄取通知後，須於 6 月 15 日台北時間晚上 8 時前完成繳費並至學員專區填寫繳費資料，才算正式錄取。', ''],
        ['報名表 > Step2 > 流程', 'register.step2.process3', '說明', '3. 正式錄取者，將建立 LINE 及微信群組。', ''],
        ['報名表 > Step2 > 流程', 'register.step2.process4', '說明', '4. 實體禪修場地條件有限，最終錄取結果由課程組決定。', ''],
        // Step 3 (Q1-Q17)
        ['報名表 > Step3', 'register.step3.title', '標題', '背景與承諾', ''],
        ['報名表 > Step3', 'register.step3.desc', '說明', '請依實際情況回答下列題目。本步驟所有 *標示者為必填。', ''],
        ['報名表 > Q1', 'register.q1.label', '題目', '1. 您是否願意承諾如實填寫本次的報名表單？', ''],
        ['報名表 > Q1', 'register.q1.options.yes', '選項', '是', ''],
        ['報名表 > Q1', 'register.q1.options.no', '選項', '否（將結束報名）', ''],
        ['報名表 > Q1', 'register.q1.msg_no', '提示', '感謝您的誠實，報名表將不予提交。', '選「否」時顯示'],
        ['報名表 > Q2', 'register.q2.label', '題目', '2. 是否以正式學員身份參加過隆波帕默尊者體系的實體或線上課程？', ''],
        ['報名表 > Q3-8', 'register.q3_8.intro', '說明', 'Q3-Q8 為各地區課程紀錄（非必選），題目格式：N. {地區} 四念處禪修課程', ''],
        ['報名表 > Q3', 'register.q3.label', '題目', '3. 泰國四念處禪修課程', '泰國・線下實體・非必選'],
        ['報名表 > Q4', 'register.q4.label', '題目', '4. 馬來西亞四念處禪修課程', '馬來西亞・線下實體・非必選'],
        ['報名表 > Q5', 'register.q5.label', '題目', '5. 《解苦心鑰》讀者交流會', '中國成都・線下實體・非必選'],
        ['報名表 > Q6', 'register.q6.label', '題目', '6. 台灣四念處禪修課程', '台灣・線下實體・非必選'],
        ['報名表 > Q7', 'register.q7.label', '題目', '7. 新加坡四念處禪修課程', '新加坡・線下實體・非必選'],
        ['報名表 > Q8', 'register.q8.label', '題目', '8. 遠程（線上）四念處禪修課程', 'Zoom・線上網路・非必選'],
        ['報名表 > Q9', 'register.q9.label', '題目', '9. 是否完整觀看／聆聽過至少 3 屆泰國四念處之旅的錄影／錄音？', ''],
        ['報名表 > Q10', 'register.q10.label', '題目', '10. 您是否透過 ZOOM 的方式，獲得阿姜巴山、阿姜納、阿姜松、阿姜妮或阿姜沃伊的一對一禪修指導？', ''],
        ['報名表 > Q11', 'register.q11.label', '題目', '11. 是否觀看／聆聽過隆波帕默尊者法談開示 30 篇以上？', ''],
        ['報名表 > Q12', 'register.q12.label', '題目', '12. 您是否持守五戒？', ''],
        ['報名表 > Q13', 'register.q13.label', '題目', '13. 您學習並實踐隆波帕默尊者的教導多久了？', ''],
        ['報名表 > Q13 選項', 'register.q13.options.opt1', '選項', '1月-3個月', ''],
        ['報名表 > Q13 選項', 'register.q13.options.opt2', '選項', '3月-6個月', ''],
        ['報名表 > Q13 選項', 'register.q13.options.opt3', '選項', '6月-1年', ''],
        ['報名表 > Q13 選項', 'register.q13.options.opt4', '選項', '1年-2年', ''],
        ['報名表 > Q13 選項', 'register.q13.options.opt5', '選項', '2年-3年', ''],
        ['報名表 > Q13 選項', 'register.q13.options.opt6', '選項', '3年-4年', ''],
        ['報名表 > Q13 選項', 'register.q13.options.opt7', '選項', '4年-5年', ''],
        ['報名表 > Q13 選項', 'register.q13.options.opt8', '選項', '5年-8年', ''],
        ['報名表 > Q13 選項', 'register.q13.options.opt9', '選項', '8年-10年', ''],
        ['報名表 > Q13 選項', 'register.q13.options.opt10', '選項', '10年以上', ''],
        ['報名表 > Q14', 'register.q14.label', '題目', '14. 過去三個月內，您做固定式練習的頻率是？', ''],
        ['報名表 > Q14 選項', 'register.q14.options.every_day', '選項', '每天至少 30 分鐘', ''],
        ['報名表 > Q14 選項', 'register.q14.options.almost_every_day', '選項', '幾乎每天，偶有間斷', ''],
        ['報名表 > Q14 選項', 'register.q14.options.commit_from_now', '選項', '未曾持續練習，但承諾自即日起每日練習 30 分鐘至 1 小時，持續至課程結束', ''],
        ['報名表 > Q15', 'register.q15.label', '題目', '15. 食宿、場地及交通等費用需由學員自行負擔，並請於 6/15 前完成支付。是否可於期限內完成？', ''],
        ['報名表 > Q15 選項', 'register.q15.options.yes', '選項', '是，我願意按時全額支付', ''],
        ['報名表 > Q16', 'register.q16.label', '題目', '16. 您是否身體健康，能夠全程獨立參與？', ''],
        ['報名表 > Q17', 'register.q17.label', '題目', '17. 您是否有心理或精神疾病史？', ''],
        ['報名表 > Q17 選項', 'register.q17.options.no', '選項', '否，無心理或精神疾病史', ''],
        ['報名表 > Q17 選項', 'register.q17.options.yes', '選項', '是，請詳細說明', ''],
        ['報名表 > Q17', 'register.q17.textarea_placeholder', 'Placeholder', '請詳細說明您的狀況', ''],
        // Step 4 (個人資訊 Q19-Q29)
        ['報名表 > Step4', 'register.step4.title', '標題', '個人資訊', ''],
        ['報名表 > Step4', 'register.step4.desc', '說明', '提供報名所需的聯絡與身份資料。所有資料僅供本次禪修使用。', ''],
        ['報名表 > Q19', 'register.q19.label', '題目', '19. 中文姓名（身分證／護照姓名）', '必填'],
        ['報名表 > Q20', 'register.q20.label', '題目', '20. 護照英文姓名', '必填'],
        ['報名表 > Q21', 'register.q21.label', '題目', '21. 您屬於？', '必填'],
        ['報名表 > Q21 選項', 'register.q21.options.lay', '選項', '在家人（居士）', ''],
        ['報名表 > Q21 選項', 'register.q21.options.monastic', '選項', '僧眾', ''],
        ['報名表 > Q22', 'register.q22.label', '題目', '22. 法名（僅出家師父填寫）', ''],
        ['報名表 > Q23', 'register.q23.label', '題目', '23. 性別', '必填'],
        ['報名表 > Q24', 'register.q24.label', '題目', '24. 年齡', '必填'],
        ['報名表 > Q25', 'register.q25.label', '題目', '25. 護照頒發地', '非必填'],
        ['報名表 > Q26', 'register.q26.label', '題目', '26. 居住地', '必填'],
        ['報名表 > Q26 選項', 'register.q26.options.taiwan', '選項', '台灣', ''],
        ['報名表 > Q26 選項', 'register.q26.options.china', '選項', '中國大陸/內地', ''],
        ['報名表 > Q26 選項', 'register.q26.options.hongkong', '選項', '香港', ''],
        ['報名表 > Q26 選項', 'register.q26.options.macau', '選項', '澳門', ''],
        ['報名表 > Q26 選項', 'register.q26.options.malaysia', '選項', '馬來西亞', ''],
        ['報名表 > Q26 選項', 'register.q26.options.thailand', '選項', '泰國', ''],
        ['報名表 > Q26 選項', 'register.q26.options.japan', '選項', '日本', ''],
        ['報名表 > Q26 選項', 'register.q26.options.usa', '選項', '美國', ''],
        ['報名表 > Q26 選項', 'register.q26.options.canada', '選項', '加拿大', ''],
        ['報名表 > Q26 選項', 'register.q26.options.singapore', '選項', '新加坡', ''],
        ['報名表 > Q26 選項', 'register.q26.options.uk', '選項', '英國', ''],
        ['報名表 > Q26 選項', 'register.q26.options.srilanka', '選項', '斯里蘭卡', ''],
        ['報名表 > Q26 選項', 'register.q26.options.other', '選項', '其他地區', ''],
        ['報名表 > Q27', 'register.q27.label', '題目', '27. 手機號碼', '必填'],
        ['報名表 > Q27', 'register.q27.hint', '提示', '海外請加國際碼，例：886+', ''],
        ['報名表 > Q28', 'register.q28.label', '題目', '28. 電子信箱', '必填'],
        ['報名表 > Q29', 'register.q29.label', '題目', '29. 通訊軟體', '必填'],
        ['報名表 > Q29', 'register.q29.hint', '提示', '必填，請於 LINE 或 微信擇一填寫並上傳對應 QR Code（檔案上限 500KB）', ''],
        ['報名表 > Q29 選項', 'register.q29.options.line', '選項', 'LINE', ''],
        ['報名表 > Q29 選項', 'register.q29.options.wechat', '選項', '微信（WeChat）', ''],
        // Step 5 / Alert / Buttons
        ['報名表 > Step5', 'register.step5.title', '標題', '確認資料', ''],
        ['報名表 > Step5', 'register.step5.desc', '說明', '請最後確認以下資料，無誤後送出。送出後可在學員專區查詢狀態。', ''],
        ['報名表 > 警示', 'register.alert.fees_title', '小標', '8/20–8/24 禪修期間之食宿、交通及場地費用', ''],
        ['報名表 > 警示', 'register.alert.fees_amount', '段落', '食宿、交通及場地費用：NT$18,600 元整（如需提前或延後住宿，將另計相關費用）', ''],
        ['報名表 > 警示', 'register.alert.fees_note', '段落', '錄取後將提供繳費連結，請於 6 月 15 日前完成繳費。', ''],
        ['報名表 > 警示', 'register.alert.reminder_title', '小標', '送出前再次提醒', ''],
        ['報名表 > 警示', 'register.alert.reminder_note1', '段落', '提交報名表後並不代表已錄取，錄取結果將於 6/6 以 Email 通知。請以您填寫的 Email 為準，注意查收（含垃圾信箱）。', ''],
        ['報名表 > 警示', 'register.alert.reminder_note2', '段落', '送出後將自動寄送一封確認信至您的 Email，內含繳費專屬碼，請妥善保管。', ''],
        ['報名表 > 按鈕', 'register.form.prev_btn', '按鈕', '← 上一步', ''],
        ['報名表 > 按鈕', 'register.form.next_btn', '按鈕', '下一步 →', ''],
        ['報名表 > 按鈕', 'register.form.submit_btn', '按鈕', '提交報名表 →', ''],
        ['報名表 > 按鈕', 'register.form.submit_loading', '按鈕', '提交中⋯ →', ''],
        ['報名表 > 按鈕', 'register.form.footer_msg', '說明', '提交後系統會將報名資訊發送到您填寫的電子信箱，請注意查收（包括垃圾郵件）。', ''],
        ['報名表 > 結尾', 'register.middle.closing', '段落', '台灣四念處學會 合十', ''],
        ['報名表 > 結尾', 'register.middle.dedication', '段落', '隨喜功德', ''],
        ['報名表 > Sidebar', 'register.sidebar.tips_note1', '說明', '請勿在 LINE 或微信內建瀏覽器中填寫，建議使用 Chrome、Safari 等瀏覽器，避免 QR Code 上傳失敗。', ''],
        ['報名表 > Sidebar', 'register.sidebar.tips_note2', '說明', '提交後系統會寄出確認信，內含您的專屬繳費碼，請妥善保管。', ''],
      ],
    },

    // ============== 學員專區 - 登入 ==============
    {
      key: 'member-login',
      title: '學員專區-登入',
      rows: [
        ['學員登入', 'member.login.title', '標題', '學員專區登入', ''],
        ['學員登入', 'member.login.subtitle', '副標', '請輸入您報名時所填寫的 E-mail 與專屬代碼。', ''],
        ['學員登入', 'member.login.subtitle.line2', '副標', '專屬代碼可於報名確認信／錄取通知信中查找。', ''],
        ['學員登入', 'member.login.email_label', '標籤', '電子信箱', ''],
        ['學員登入', 'member.login.email_placeholder', 'Placeholder', '您報名時所填寫的 Email', ''],
        ['學員登入', 'member.login.code_label', '標籤', '專屬代碼', ''],
        ['學員登入', 'member.login.code_placeholder', 'Placeholder', '例：MMN85PUN', ''],
        ['學員登入', 'member.login.code_hint', '提示', '請參考錄取通知信中的專屬代碼，不分大小寫。', ''],
        ['學員登入', 'member.login.submit_button', '按鈕', '進入學員專區', ''],
        ['學員登入', 'member.login.submit_loading', '按鈕', '登入中⋯', ''],
        ['學員登入', 'member.login.help_prefix', '段落', '遺失專屬代碼？', ''],
        ['學員登入', 'member.login.help_link', '連結', '寫信給我們', ''],
        ['學員登入', 'member.login.nav_back', '連結', '← 返回首頁', ''],
      ],
    },

    // ============== 學員專區 - Dashboard ==============
    {
      key: 'dashboard',
      title: '學員專區-Dashboard',
      rows: [
        ['Dashboard > 歡迎', 'dashboard.welcome.greeting', '標題', 'Welcome Back · 歡迎回來', ''],
        ['Dashboard > 歡迎', 'dashboard.welcome.approved_status', '段落', '您已通過資格審核，請依下方狀態完成各項待辦。', ''],
        ['Dashboard > 歡迎', 'dashboard.welcome.pending_status', '段落', '感謝您的報名，您的資料正在審核中。', ''],
        ['Dashboard > 狀態', 'dashboard.status.approved', '狀態', '已錄取', ''],
        ['Dashboard > 狀態', 'dashboard.status.pending', '狀態', '審核中', ''],
        ['Dashboard > 狀態', 'dashboard.status.rejected', '狀態', '未錄取', ''],
        ['Dashboard > 公告', 'dashboard.announce.title', '標題', '最新公告', ''],
        ['Dashboard > 公告', 'dashboard.announce.body', '段落', '錄取通知已發送，請於 6/15 晚上 8 時前完成繳費，並於 6/20 晚上 8 時前食宿登記，才算正式錄取。', '組合句'],
        ['Dashboard > 進度', 'dashboard.progress.title', '標題', '完成度進度', ''],
        // Cards
        ['Dashboard > 繳費卡', 'dashboard.payment.title', '標題', '繳費', ''],
        ['Dashboard > 繳費卡', 'dashboard.payment.deadline', '段落', '06/15 晚上 8 時前', ''],
        ['Dashboard > 繳費卡', 'dashboard.payment.status_done', '狀態', '已完成', ''],
        ['Dashboard > 繳費卡', 'dashboard.payment.status_pending', '狀態', '待確認', ''],
        ['Dashboard > 繳費卡', 'dashboard.payment.status_unpaid', '狀態', '待繳費', ''],
        ['Dashboard > 繳費卡', 'dashboard.payment.action_done', '按鈕', '查看', ''],
        ['Dashboard > 繳費卡', 'dashboard.payment.action_pending', '按鈕', '前往繳費 →', ''],
        ['Dashboard > 食宿卡', 'dashboard.lodging.title', '標題', '食宿登記', ''],
        ['Dashboard > 食宿卡', 'dashboard.lodging.deadline', '段落', '06/20 晚上 8 時前', ''],
        ['Dashboard > 食宿卡', 'dashboard.lodging.status_locked', '狀態', '已鎖定', ''],
        ['Dashboard > 食宿卡', 'dashboard.lodging.status_editable', '狀態', '可改 1 次', ''],
        ['Dashboard > 食宿卡', 'dashboard.lodging.status_empty', '狀態', '待填寫', ''],
        ['Dashboard > 食宿卡', 'dashboard.lodging.action_empty', '按鈕', '前往登記 →', ''],
        ['Dashboard > 快篩卡', 'dashboard.tests.title', '標題', '快篩上傳', ''],
        ['Dashboard > 快篩卡', 'dashboard.tests.deadline', '段落', '8/17 晚上 8 點 ／ 8/19 中午 12 點前', ''],
        ['Dashboard > 互動報名卡', 'dashboard.interactive.title', '標題', '互動報名', ''],
        ['Dashboard > 互動報名卡', 'dashboard.interactive.deadline', '段落', '07/15 晚上 8 點前', ''],
        ['Dashboard > 互動報名卡', 'dashboard.interactive.action_done', '按鈕', '查看／修改', ''],
        ['Dashboard > 互動報名卡', 'dashboard.interactive.action_pending', '按鈕', '前往報名 →', ''],
        ['Dashboard > 互動作業卡', 'dashboard.task.title', '標題', '互動作業', ''],
        ['Dashboard > 互動作業卡', 'dashboard.task.deadline', '段落', '課程開始前完成', ''],
        ['Dashboard > 承諾書卡', 'dashboard.pledge.title', '標題', '承諾書', ''],
        ['Dashboard > 承諾書卡', 'dashboard.pledge.deadline', '段落', '現場簽署繳交（不需線上送出）', ''],
        ['Dashboard > 承諾書卡', 'dashboard.pledge.action', '按鈕', '下載承諾書 ↓', ''],
        ['Dashboard > 審核中', 'dashboard.pending.title', '標題', '報名審核中', ''],
        ['Dashboard > 審核中', 'dashboard.pending.desc1', '段落', '您的報名資料已收到，學會正在審核。錄取通知將於 06/06 以 Email 發送，請留意收件匣與垃圾信箱。', ''],
        ['Dashboard > 審核中', 'dashboard.pending.desc2', '段落', '在錄取確認前，請勿購買機票或安排行程。', ''],
        ['Dashboard > 未錄取', 'dashboard.rejected.title', '標題', '未錄取本次禪修', ''],
        ['Dashboard > 未錄取', 'dashboard.rejected.desc', '段落', '感謝您的報名意願。本次禪修因名額限制，您未能錄取。歡迎下次再報名，或先參加每月 ZOOM 線上指導老師互動。', ''],
      ],
    },

    // ============== 食宿登記 ==============
    {
      key: 'lodging',
      title: '食宿登記表',
      rows: [
        ['食宿 > 頁首', 'lodging.page.title', '標題', '食宿登記表', ''],
        ['食宿 > 頁首', 'lodging.page.subtitle1', '副標', '請於 6 月 20 日台北時間晚上 8 點前完成。', ''],
        ['食宿 > 頁首', 'lodging.page.subtitle2', '副標', '送出後僅能再修改一次（共 2 次送出機會）。', ''],
        ['食宿 > 步驟', 'lodging.step1.title', '步驟標題', '行程安排', ''],
        ['食宿 > 步驟', 'lodging.step2.title', '步驟標題', '飲食偏好', ''],
        ['食宿 > 步驟', 'lodging.step3.title', '步驟標題', '證件上傳', ''],
        ['食宿 > 步驟', 'lodging.step4.title', '步驟標題', '確認送出', ''],
        // Step1 重要提醒
        ['食宿 > 重要提醒', 'lodging.step1.alert.1', '警示', '請慎重考慮並如實填寫。由於飯店條款限制，學會已先代墊食宿等費用，若取消報名，所付費用恕不退款、轉讓。', ''],
        ['食宿 > 重要提醒', 'lodging.step1.alert.2', '警示', '本表單送出後僅能再修改一次（共 2 次送出機會），請務必確認後再送出。', ''],
        // 會館入住
        ['食宿 > 入住說明', 'lodging.step1.hotel.1', '段落', '日月潭會館辦理入住時間：每日下午 3 點後辦理入住。', ''],
        ['食宿 > 入住說明', 'lodging.step1.hotel.2', '段落', '辦理入住時請攜帶身分證 + 健保卡（國內）或護照正本（國外）。', ''],
        ['食宿 > 入住說明', 'lodging.step1.hotel.3', '段落', '房間一律 4 人一房，採單獨床位配置，附 2 套衛浴。', ''],
        ['食宿 > 入住說明', 'lodging.step1.hotel.4', '段落', '每間房間皆有對外窗戶，舒適寬敞，可曬衣。', ''],
        ['食宿 > 入住說明', 'lodging.step1.hotel.5', '段落', '請自備盥洗用具、衣架與雨具，會館不提供一次性盥洗用品。', ''],
        // 緊急聯絡人
        ['食宿 > 緊急聯絡人', 'lodging.emergency_name.label', '題目', '姓名', '必填'],
        ['食宿 > 緊急聯絡人', 'lodging.emergency_relation.label', '題目', '關係', '必填'],
        ['食宿 > 緊急聯絡人', 'lodging.emergency_relation.placeholder', 'Placeholder', '例：配偶、父母、朋友', ''],
        ['食宿 > 緊急聯絡人', 'lodging.emergency_phone.label', '題目', '聯絡電話', '必填'],
        ['食宿 > 緊急聯絡人', 'lodging.emergency_phone.placeholder', 'Placeholder', '請加國碼，例：886+', ''],
        // 前往日月潭
        ['食宿 > 前往方式', 'lodging.transport.self', '選項', '8/19 自行抵達日月潭湖畔會館', ''],
        ['食宿 > 前往方式', 'lodging.transport.taipei_bus', '選項', '主辦專車：8/19 上午 8:30 台北車站東 3 門集合', ''],
        ['食宿 > 前往方式', 'lodging.transport.wuri_bus', '選項', '主辦專車：8/19 上午 9:30 烏日高鐵站 6 號出口', ''],
        ['食宿 > 前往方式', 'lodging.transport.airport_bus_0819', '選項', '主辦專車：8/19 下午 2:30 桃園機場第一航廈', ''],
        ['食宿 > 前往方式', 'lodging.transport.self_0820', '選項', '8/20 上午 7 點前自行抵達日月潭湖畔會館', ''],
        // 國外計程車
        ['食宿 > 國外提示', 'lodging.foreign.alert.title', '小標', '國外學員自行前往可聯絡', ''],
        ['食宿 > 國外提示', 'lodging.foreign.taxi1', '段落', '桃園機場計程車預約電話：03-3834499', ''],
        ['食宿 > 國外提示', 'lodging.foreign.taxi2', '段落', '台灣大車隊計程車手機直撥：55688', ''],
        ['食宿 > 國外提示', 'lodging.foreign.taxi3', '段落', '大都會計程車手機直撥：55178', ''],
        // 離開
        ['食宿 > 離開方式', 'lodging.bus_dest.taipei_824_pm', '選項', '8/24 下午 6:00–6:30 專車到台北車站', ''],
        ['食宿 > 離開方式', 'lodging.bus_dest.taipei_825_am', '選項', '8/25 上午 9:00 專車到台北車站', ''],
        ['食宿 > 離開方式', 'lodging.bus_dest.wuri_825_am', '選項', '8/25 上午 9:00 專車到烏日高鐵', ''],
        ['食宿 > 離開方式', 'lodging.bus_dest.taoyuan_824_pm', '選項', '8/24 下午 6:00–6:30 專車到桃園機場第一航廈', ''],
        ['食宿 > 離開方式', 'lodging.bus_dest.taoyuan_825_am', '選項', '8/25 上午 9:00 專車到桃園機場第一航廈', ''],
        // Step2 飲食
        ['食宿 > 飲食', 'lodging.diet.meat', '選項', '葷食', ''],
        ['食宿 > 飲食', 'lodging.diet.vegetarian', '選項', '素食', ''],
        ['食宿 > 過午不食', 'lodging.noon.before_noon', '選項', '需要 12 點前吃', ''],
        ['食宿 > 過午不食', 'lodging.noon.after_noon', '選項', '可以 12 點後吃', ''],
        ['食宿 > 茶點', 'lodging.snacks.snacks_and_drink', '選項', '需要茶點、咖啡 OR 茶', ''],
        ['食宿 > 茶點', 'lodging.snacks.drink_only', '選項', '只需要咖啡 OR 茶', ''],
        ['食宿 > 晚餐', 'lodging.dinner_0819', '選項', '8/19 需要在日月潭會館用晚餐', ''],
        ['食宿 > 晚餐', 'lodging.dinner_0824', '選項', '8/24 晚上 5–6 點需要在日月潭會館用晚餐', ''],
        // Step3
        ['食宿 > Step3', 'lodging.step3.desc', '說明', '支援 JPG / PNG / WEBP / PDF（5MB 以下）。請依您的身份類別上傳對應證件。', ''],
        ['食宿 > 個人相片', 'lodging.photo.label', '題目', '個人相片（最近 3 個月內，勿使用美顏）', '必填'],
        ['食宿 > 身份類別', 'lodging.identity.id', '選項', '台灣人（上傳身分證正反面）', ''],
        ['食宿 > 身份類別', 'lodging.identity.passport', '選項', '外籍短期旅客', '觀光／免簽／短期簽證入境，上傳護照 + 填寫航班資訊'],
        ['食宿 > 身份類別', 'lodging.identity.arc', '選項', '在台外籍居民（上傳 ARC／居留證）', ''],
        ['食宿 > 證件', 'lodging.id_front.label', '題目', '身分證正面', '台灣人必填'],
        ['食宿 > 證件', 'lodging.id_back.label', '題目', '身分證反面', '台灣人必填'],
        ['食宿 > 證件', 'lodging.passport.label', '題目', '護照', '外籍旅客必填'],
        ['食宿 > 證件', 'lodging.arc.label', '題目', 'ARC／居留證', '外籍居民必填'],
        ['食宿 > 航班', 'lodging.flight.title', '小標', '航班資訊（外籍短期旅客必填）', ''],
        ['食宿 > 航班', 'lodging.flight_arrival_date.label', '題目', '抵台航班日期（入境日）', ''],
        ['食宿 > 航班', 'lodging.flight_arrival_time.label', '題目', '抵台航班具體時間', ''],
        ['食宿 > 航班', 'lodging.flight_departure_date.label', '題目', '離台航班日期（離境日）', ''],
        ['食宿 > 航班', 'lodging.flight_departure_time.label', '題目', '離台航班具體時間', ''],
        ['食宿 > 機票', 'lodging.arrival_ticket.label', '題目', '上傳來台機票（非必填）', ''],
        ['食宿 > 機票', 'lodging.departure_ticket.label', '題目', '上傳離台機票（非必填）', ''],
        ['食宿 > 快篩說明', 'lodging.quicktest.desc', '段落', '快篩檢測時程在課程開始前後（8/17、8/19、8/20、8/22）。請完成本食宿登記後，另行於專屬頁面上傳。確認信中會附上快篩上傳頁連結。', ''],
        // Step4 防疫規範
        ['食宿 > 規範', 'lodging.rules.infectious.1', '段落', '若在課程前幾天感冒確診並仍具傳染力，必須取消課程。', ''],
        ['食宿 > 規範', 'lodging.rules.infectious.2', '段落', '若在課程會場被檢驗出陽性，同寢室 4 人需在房間隔離，並透過 ZOOM 線上上課及互動。', ''],
        ['食宿 > 規範', 'lodging.rules.infectious.3', '段落', '若出現發燒、咳嗽、呼吸急促、胸悶、頭痛、喉嚨痛等症狀，需接受個別檢測；即使陰性亦會移至後段座位。', ''],
        ['食宿 > 規範', 'lodging.rules.testing.1', '段落', '檢測結果必須載明檢測日期、報名序號、姓名，快篩試劑請自備。', ''],
        ['食宿 > 規範', 'lodging.rules.testing.2', '段落', '開課前：8/17 上午 8:00 ～ 晚上 8:00 前上傳、8/19 上午 12:00 前上傳（於快篩頁上傳）', ''],
        ['食宿 > 規範', 'lodging.rules.testing.3', '段落', '課程期間：8/20、8/22 上午 8:00 前現場繳交（不需線上上傳）', ''],
        ['食宿 > 規範', 'lodging.rules.course.1', '段落', '課程期間全程配戴口罩。', ''],
        ['食宿 > 規範', 'lodging.rules.course.2', '段落', '課程期間一律停用手機等通訊設備。', ''],
        ['食宿 > 規範', 'lodging.rules.course.3', '段落', '用餐時必須禁語。', ''],
        ['食宿 > 規範', 'lodging.rules.course.4', '段落', '請務必全程佩戴學員證。', ''],
        ['食宿 > 規範', 'lodging.rules.course.5', '段落', '為示尊重，未得老師允許，上課中請勿拍照、攝影或錄音。', ''],
        ['食宿 > 規範', 'lodging.rules.course.6', '段落', '本次課程所有座位皆是座椅，請勿佔座位，離開時請記得將個人物品帶走。', ''],
        ['食宿 > 規範', 'lodging.rules.course.7', '段落', '請勿攜帶貴重物品至會場，個人隨身物品請自行妥善保管。', ''],
        ['食宿 > 規範', 'lodging.rules.course.8', '段落', '請穿著整齊、舒適且適宜聞法的衣著。', ''],
        ['食宿 > 規範', 'lodging.rules.course.9', '段落', '會場長時開著冷氣，畏寒者可攜帶禦寒衣物（如圍巾、披肩、襪子等）。', ''],
        ['食宿 > 規範', 'lodging.agree.label', '勾選', '我已閱讀並願意遵守以上防疫與課程規範', ''],
        ['食宿 > 其他', 'lodging.snoring.label', '勾選', '睡覺會打鼾（提供同寢室友參考）', ''],
        // 按鈕 / 狀態
        ['食宿 > 按鈕', 'lodging.button.submit', '按鈕', '提交食宿登記', ''],
        ['食宿 > 按鈕', 'lodging.button.submit_edit', '按鈕', '送出修改（最後 1 次）', ''],
        ['食宿 > 截止', 'lodging.status.deadline', '狀態', '食宿登記已截止', ''],
        ['食宿 > 截止', 'lodging.status.deadline_desc', '段落', '食宿登記已於 6/20 晚上 8 點截止，請聯絡學會。', ''],
      ],
    },

    // ============== 快篩上傳 ==============
    {
      key: 'quicktests',
      title: '快篩上傳',
      rows: [
        ['快篩 > 頁首', 'quicktests.page.title', '標題', '快篩檢測上傳', ''],
        ['快篩 > 頁首', 'quicktests.page.subtitle1', '副標', '8/17 與 8/19 兩個時段的快篩結果請於規定時間前上傳；可分次回到此頁補上。', ''],
        ['快篩 > 頁首', 'quicktests.page.subtitle2', '副標', '8/20、8/22 課程期間的快篩結果請於現場繳交。', ''],
        ['快篩 > 8/17', 'quicktests.0817.label', '標題', '8/17 快篩上傳', ''],
        ['快篩 > 8/17', 'quicktests.0817.deadline', '說明', '8/17 上午 8 點 ～ 晚上 8 點前', ''],
        ['快篩 > 8/19', 'quicktests.0819.label', '標題', '8/19 快篩上傳', ''],
        ['快篩 > 8/19', 'quicktests.0819.deadline', '說明', '8/19 上午 12 點前', ''],
        ['快篩 > 注意', 'quicktests.alert.1', '段落', '檢測結果必須載明檢測日期、報名序號、姓名。', ''],
        ['快篩 > 注意', 'quicktests.alert.2', '段落', '快篩試劑請自備，主辦單位不提供。', ''],
        ['快篩 > 注意', 'quicktests.alert.3', '段落', '請依下方兩個時段於規定時間前上傳；可分次回到此頁補上。', ''],
        ['快篩 > 注意', 'quicktests.alert.4', '段落', '課程期間的 8/20、8/22 快篩結果現場繳交，不需於此上傳。', ''],
        ['快篩 > 完成', 'quicktests.done.title', '標題', '快篩上傳已收到', ''],
        ['快篩 > 完成', 'quicktests.done.desc', '段落', '系統已寄出確認信至您的 Email。未上傳的時段請於規定時間前回到此頁補上。', ''],
        ['快篩 > 提醒', 'quicktests.tips.1', '段落', '檢測結果必須載明檢測日期、報名序號、姓名，建議手寫於試劑旁再拍照。', ''],
        ['快篩 > 提醒', 'quicktests.tips.2', '段落', '快篩試劑請自備，主辦單位不提供。', ''],
        ['快篩 > 提醒', 'quicktests.tips.3', '段落', '課程期間 8/20、8/22 改現場繳交，毋須線上上傳。', ''],
      ],
    },

    // ============== 繳費頁 ==============
    {
      key: 'pay',
      title: '繳費頁',
      rows: [
        ['繳費 > 頁首', 'pay.page.title', '標題', '食宿費用繳費', ''],
        ['繳費 > 頁首', 'pay.page.subtitle1', '副標', '請於 6 月 15 日台北時間晚上 8 點前完成繳費。', ''],
        ['繳費 > 頁首', 'pay.page.subtitle2', '副標', '繳費完成後系統會寄信邀請您完成食宿登記，方案內容會自動帶入食宿登記表。', ''],
        // Plans
        ['繳費 > 方案 A1', 'pay.plan.A1.label', '段落', 'A 方案 ／ 8/20 — 8/24 食宿等費用 ／ NT$18,600 ／ 匯款', ''],
        ['繳費 > 方案 A2', 'pay.plan.A2.label', '段落', 'A 方案 ／ 8/20 — 8/24 食宿等費用 ／ NT$19,300 ／ 信用卡刷卡', ''],
        ['繳費 > 方案 B1', 'pay.plan.B1.label', '段落', 'B 方案 ／ 8/19 — 8/24 食宿費用 ／ NT$20,350 ／ 匯款', ''],
        ['繳費 > 方案 B2', 'pay.plan.B2.label', '段落', 'B 方案 ／ 8/19 — 8/24 食宿費用 ／ NT$21,050 ／ 信用卡刷卡', ''],
        ['繳費 > 方案 C1', 'pay.plan.C1.label', '段落', 'C 方案 ／ 8/19 — 8/25 食宿等費用 ／ NT$22,590 ／ 匯款', ''],
        ['繳費 > 方案 C2', 'pay.plan.C2.label', '段落', 'C 方案 ／ 8/19 — 8/25 食宿等費用 ／ NT$23,290 ／ 信用卡刷卡', ''],
        ['繳費 > 方案 D1', 'pay.plan.D1.label', '段落', 'D 方案 ／ 8/20 — 8/25 食宿等費用 ／ NT$20,840 ／ 匯款', ''],
        ['繳費 > 方案 D2', 'pay.plan.D2.label', '段落', 'D 方案 ／ 8/20 — 8/25 食宿等費用 ／ NT$21,540 ／ 信用卡刷卡', ''],
        // Alert
        ['繳費 > 警示', 'pay.alert.title', '小標', '繳費前請務必確認', ''],
        ['繳費 > 警示', 'pay.alert.1', '警示', '請於 2026/06/15 晚上 8 點前（台北時間）完成繳費。', ''],
        ['繳費 > 警示', 'pay.alert.2', '警示', '一旦繳費後取消報名，已付費用恕無法退款或轉讓。', ''],
        ['繳費 > 警示', 'pay.alert.3', '警示', '方案內容會自動帶入食宿登記表，請選擇對應的入住天數。', ''],
        // 按鈕
        ['繳費 > 按鈕', 'pay.button.transfer', '按鈕', '查看匯款帳號', ''],
        ['繳費 > 按鈕', 'pay.button.card', '按鈕', '前往綠界刷卡付款', ''],
        ['繳費 > 狀態', 'pay.status.verified', '狀態', '繳費已確認', ''],
        ['繳費 > 狀態', 'pay.status.verified_desc', '段落', '您的繳費資料已由學會確認，本頁僅供參考。如有疑問請聯絡學會。', ''],
        ['繳費 > 狀態', 'pay.status.pending', '狀態', '繳費資訊已回報，待學會確認', ''],
        // 匯款帳號
        ['繳費 > 匯款', 'pay.bank.domestic.title', '小標', '本國 台灣法友匯款', ''],
        ['繳費 > 匯款', 'pay.bank.domestic.name', '段落', '戶名：台灣四念處學會', ''],
        ['繳費 > 匯款', 'pay.bank.domestic.bank', '段落', '銀行：第一銀行 仁和分行（代號 007）', ''],
        ['繳費 > 匯款', 'pay.bank.domestic.account', '段落', '帳號：16510068750', ''],
        ['繳費 > 匯款', 'pay.bank.overseas.title', '小標', '海外 國外法友匯款', ''],
        ['繳費 > 匯款', 'pay.bank.overseas.account', '段落', '帳號：16540016022', ''],
        ['繳費 > 匯款', 'pay.bank.alert.1', '警示', '匯款時請備注您的姓名及繳費碼：{繳費碼}', '保留 {繳費碼} 變數'],
        ['繳費 > 匯款', 'pay.bank.alert.2', '警示', '匯款完成後請填寫下方匯款資訊回報，並截圖上傳至學會 LINE 官方帳號。', ''],
        ['繳費 > 匯款回報', 'pay.bank.last5.label', '題目', '匯款帳號後 5 碼', ''],
        ['繳費 > 匯款回報', 'pay.bank.last5.placeholder', 'Placeholder', '5 位數字', ''],
        ['繳費 > 匯款回報', 'pay.bank.date.label', '題目', '匯款日期', ''],
        ['繳費 > 匯款回報', 'pay.bank.account_name.label', '題目', '匯款人姓名', ''],
        ['繳費 > 匯款回報', 'pay.button.submit_transfer', '按鈕', '確認提交匯款資訊', ''],
        ['繳費 > 提醒', 'pay.tips.1', '段落', '匯款方案：請務必於匯款備註中填寫您的姓名與繳費碼，並於下方回填匯款後 5 碼。', ''],
        ['繳費 > 提醒', 'pay.tips.2', '段落', '刷卡方案：將跳轉到綠界第三方加密頁面，學會不會接觸您的卡號。', ''],
        ['繳費 > 提醒', 'pay.tips.3', '段落', '已繳費後取消報名，已付費用恕無法退款、轉讓。', ''],
      ],
    },

    // ============== 互動報名 ==============
    {
      key: 'interactive',
      title: '互動報名',
      rows: [
        ['互動報名 > 頁首', 'interactive.page.title', '標題', '互動報名', ''],
        ['互動報名 > 頁首', 'interactive.page.subtitle1', '副標', '登記您希望參加的集體互動場次與分組互動的優先順序。', ''],
        ['互動報名 > 頁首', 'interactive.page.subtitle2', '副標', '送出後可於截止前重新送出修改。', ''],
        // 步驟
        ['互動報名 > 步驟', 'interactive.step1.label', '步驟', '規則說明', ''],
        ['互動報名 > 步驟', 'interactive.step2.label', '步驟', '集體互動', ''],
        ['互動報名 > 步驟', 'interactive.step3.label', '步驟', '分組互動', ''],
        // Banner
        ['互動報名 > 未開放', 'interactive.closed_banner.title', 'Banner', '互動報名尚未開放', ''],
        ['互動報名 > 未開放', 'interactive.closed_banner.desc', '段落', '互動報名尚未開放，學會將另行寄信通知開放時間，請留意您的 Email。如有疑問請聯絡學會。', ''],
        ['互動報名 > 截止', 'interactive.deadline_banner.title', 'Banner', '互動報名已截止', ''],
        ['互動報名 > 截止', 'interactive.deadline_banner.desc', '段落', '互動報名已於 7/15 晚上 8 點（台北時間）截止，無法再提交。', ''],
        ['互動報名 > 已送出', 'interactive.done_banner.title', 'Banner', '互動報名已送出', ''],
        ['互動報名 > 已送出', 'interactive.done_banner.desc', '段落', '送出時間：{時間}　·　如需修改請於 7/15 截止前重新送出', '保留 {時間} 變數'],
        ['互動報名 > 預覽', 'interactive.preview_banner.title', 'Banner', '後台預覽模式', ''],
        ['互動報名 > 預覽', 'interactive.preview_banner.desc', '段落', '此頁尚未對學員開放，您（admin）以預覽身分操作，送出的內容會真實寫入此學員的互動報名。請使用測試學員，並於開放前清理測試資料。', ''],
        // Step1
        ['互動報名 > Step1 集體', 'interactive.step1.group.title', '小標', '集體互動', ''],
        ['互動報名 > Step1 集體', 'interactive.step1.group.rule1', '段落', '所有學員均可自願報名參加集體互動', ''],
        ['互動報名 > Step1 集體', 'interactive.step1.group.rule2', '段落', '集體互動名額有限，最終互動及候補名單將按場次順序，通過隨機抽籤產生', ''],
        ['互動報名 > Step1 分組', 'interactive.step1.small.title', '小標', '分組互動', ''],
        ['互動報名 > Step1 分組', 'interactive.step1.small.rule1', '段落', '請所有學員根據自身的互動與學習意願，對四個小組進行優先級排序', ''],
        ['互動報名 > Step1 分組', 'interactive.step1.small.rule2', '段落', '各組名額有限，優先按學員的第一意願進行分配', ''],
        ['互動報名 > Step1 分組', 'interactive.step1.small.rule3', '段落', '若報名人數超出該組名額，則在第一意願申請者中進行抽籤；未能中籤的學員，將依次按其第二、第三意願參與抽籤', ''],
        ['互動報名 > Step1 名額', 'interactive.step1.quota.rule1', '段落', '所有學員可同時報名集體互動與分組互動', ''],
        ['互動報名 > Step1 名額', 'interactive.step1.quota.rule2', '段落', '每位學員均有一次分組互動的機會；集體互動名額則通過抽籤決定', ''],
        // Step2 場次
        ['互動報名 > 場次 s1', 'interactive.session.s1', '段落', '8/21（週五）14:00 — 15:30　阿姜巴山（8 人）', ''],
        ['互動報名 > 場次 s2', 'interactive.session.s2', '段落', '8/21（週五）14:00 — 15:30　阿姜納（8 人）', ''],
        ['互動報名 > 場次 s3', 'interactive.session.s3', '段落', '8/22（週六）14:00 — 15:30　阿姜妮（8 人）', ''],
        ['互動報名 > 場次 s4', 'interactive.session.s4', '段落', '8/22（週六）14:00 — 15:30　阿姜松（8 人）', ''],
        ['互動報名 > 場次 s5', 'interactive.session.s5', '段落', '8/23（週日）14:00 — 15:30　阿姜巴山（8 人）', ''],
        ['互動報名 > 場次 s6', 'interactive.session.s6', '段落', '8/23（週日）14:00 — 15:30　阿姜妮（8 人）', ''],
        ['互動報名 > Step2', 'interactive.step2.header_desc', '段落', '請選擇您希望報名的場次（可複選或保持空白）。最終以隨機抽籤產生名單。', ''],
        // Step3
        ['互動報名 > Step3', 'interactive.step3.header_desc', '段落', '將右側老師加入左側順位欄。順位 1 = 第一意願，順位 4 = 第四意願。可全部不填代表不參加分組互動。', ''],
        ['互動報名 > Step3 提醒', 'interactive.step3.alert', '說明', '點擊右側老師加入下一個空欄；已填入的老師可點 ✕ 移回右側。要報名分組互動請排滿 4 位（必須完整排序），不報名則保持空白。', ''],
        ['互動報名 > Step3 老師', 'interactive.teacher.prasan', '段落', '阿姜巴山', ''],
        ['互動報名 > Step3 老師', 'interactive.teacher.nat', '段落', '阿姜納', ''],
        ['互動報名 > Step3 老師', 'interactive.teacher.nitiya', '段落', '阿姜妮', ''],
        ['互動報名 > Step3 老師', 'interactive.teacher.napatpol', '段落', '阿姜松', ''],
        // 提醒
        ['互動報名 > 提醒', 'interactive.tips.tip1', '段落', '集體互動可全部不勾，代表不報名集體互動。', ''],
        ['互動報名 > 提醒', 'interactive.tips.tip2', '段落', '分組互動要排序就要排完整 4 位，不報則保持空白。', ''],
        ['互動報名 > 提醒', 'interactive.tips.tip3', '段落', '抽籤結果由學會於互動報名截止後寄信通知。', ''],
        // 按鈕
        ['互動報名 > 按鈕', 'interactive.btn.submit', '按鈕', '送出互動報名', ''],
        ['互動報名 > 按鈕', 'interactive.btn.submit_edit', '按鈕', '送出修改', ''],
      ],
    },

    // ============== 互動作業 ==============
    {
      key: 'interactive-task',
      title: '互動作業',
      rows: [
        ['互動作業 > 頁首', 'task.page.title', '標題', '互動作業', ''],
        ['互動作業 > 頁首', 'task.page.subtitle1', '副標', '請填寫您近期的實修狀況，老師會依此準備指導。', ''],
        ['互動作業 > 頁首', 'task.page.subtitle2', '副標', '每題互動問題限 75 字內。', ''],
        ['互動作業 > 步驟', 'task.step1.label', '步驟', '基本資料', ''],
        ['互動作業 > 步驟', 'task.step2.label', '步驟', '集體互動', ''],
        ['互動作業 > 步驟', 'task.step3.label', '步驟', '分組互動', ''],
        ['互動作業 > Banner', 'task.notWon.title', '標題', '本頁僅限互動中簽者', ''],
        ['互動作業 > Banner', 'task.notWon.desc', '段落', '您目前的互動報名結果尚未中簽，互動作業僅限中簽者填寫。如有疑問請聯絡學會。', ''],
        // Step1
        ['互動作業 > Step1', 'task.step1.desc', '說明', '您的身份資料由系統自動帶入。請填寫實修背景。', ''],
        ['互動作業 > Q05', 'task.q05.label', '題目', '05. 您學習並實踐隆波帕默尊者的教導多長時間了？', '必填'],
        ['互動作業 > Q05', 'task.q05.placeholder', 'Placeholder', '例：3 年、半年、剛開始等', ''],
        ['互動作業 > Q06', 'task.q06.label', '題目', '06. 請填寫您固定形式的練習方法、頻率和時長', '必填'],
        ['互動作業 > Q06', 'task.q06.hint', '提示', '如果是念誦請註明內容；如同時採用兩種以上練習也請註明（例如：每日經行 1 小時 + 念誦半小時）', ''],
        ['互動作業 > Q06', 'task.q06.placeholder', 'Placeholder', '例：每日經行三小時、靜坐一小時，每週至少 5 天', ''],
        ['互動作業 > Q07', 'task.q07.label', '題目', '07. 請填寫您在日常生活中的練習方法', '必填'],
        ['互動作業 > Q07', 'task.q07.hint', '提示', '例如：觀身體的動停、念誦（請註明念誦的內容）等', ''],
        ['互動作業 > Q07', 'task.q07.placeholder', 'Placeholder', '例：在通勤、用餐、工作中保持覺察身體的動作', ''],
        // Step2
        ['互動作業 > Step2', 'task.step2.header_desc', '段落', '請就您中簽的集體場次填寫問題。', ''],
        ['互動作業 > Q09', 'task.q09.label', '題目', '09. 您是否曾與這位指導老師互動過？', '必填'],
        ['互動作業 > Q10', 'task.q10.label', '題目', '10. 請填寫您近期的實修情況以及希望這位老師指導的實修中出現的問題', '必填，限 75 字'],
        ['互動作業 > Q10', 'task.q10.hint', '提示', '限 75 字內。互動是由老師針對您當前實修狀態給予指導的機會。請不要提交：①和實修無關的內容；②已過去很久的境界；③純理論。', ''],
        ['互動作業 > Q10', 'task.q10.placeholder', 'Placeholder', '例：最近固定模式經常昏昏沉沉，覺性也慢，心重苦比較多，心力弱。請老師指點突破。', ''],
        // Step3
        ['互動作業 > Step3', 'task.step3.header_desc', '段落', '請就您中簽的分組填寫問題。', ''],
        ['互動作業 > Q13', 'task.q13.label', '題目', '13. 您是否曾與這位指導老師互動過？', '必填'],
        ['互動作業 > Q15', 'task.q15.label', '題目', '15. 請填寫您近期的實修情況以及希望這位老師指導的實修中出現的問題', '必填，限 75 字'],
        ['互動作業 > Q15', 'task.q15.hint', '提示', '限 75 字內。同上互動規範。', ''],
        // 提醒
        ['互動作業 > 提醒', 'task.tips.1', '段落', '互動問題限 75 字內，請聚焦於當前實修狀態與具體疑問。', ''],
        ['互動作業 > 提醒', 'task.tips.2', '段落', '避免：①與實修無關的內容；②過去很久的境界；③純理論。', ''],
        ['互動作業 > 提醒', 'task.tips.3', '段落', '送出後可繼續修改，老師會於課前準備指導。', ''],
      ],
    },

    // ============== Email：錄取通知信 ==============
    {
      key: 'email-approval',
      title: 'Email-錄取通知信',
      rows: [
        ['錄取信 > 主旨', 'approval.subject', '主旨', '【第二屆台灣四念處禪修】錄取通知', ''],
        ['錄取信 > 表頭', 'approval.h1', '主標', '第二屆台灣四念處禪修課程－錄取通知', ''],
        ['錄取信 > 開場', 'approval.greeting', '段落', '{姓名} 法友您好：', '保留 {姓名}'],
        ['錄取信 > 開場', 'approval.summary', '段落', '恭喜您被錄取成為「第二屆台灣四念處禪修課程」學員，您的報名序號為 {報名序號}。', '保留 {報名序號}'],
        ['錄取信 > 一、', 'approval.section1.heading', '段標', '一、請詳讀以下內容', ''],
        ['錄取信 > 一、', 'approval.section1.para', '段落', '本信包含：繳費資訊、費用方案、食宿登記、快篩檢測、承諾書、住宿安排、報到時間、課程時間、結束時間、禪修課程群組、承諾事宜、海外入境須知、航班建議等。請務必逐項閱讀。', ''],
        ['錄取信 > 二、', 'approval.section2.heading', '段標', '二、繳費 / 食宿登記 / 快篩 / 承諾書', ''],
        ['錄取信 > 二、', 'approval.section2.intro', '段落', '以下流程可獨立進行、不需依序。前三項為線上完成，第四項為下載列印後現場繳交。互動報名將另行寄信通知開放時間。', ''],
        ['錄取信 > ① 繳費', 'approval.payment.heading', '小標', '① 繳費　截止：6 月 15 日台北時間晚上 8 時前', ''],
        ['錄取信 > ① 繳費', 'approval.payment.button', '按鈕', '前往繳費', ''],
        ['錄取信 > ① 繳費', 'approval.payment.warning', '警示', '匯款／轉帳前請慎重考慮！由於飯店條款限制，學會已先代墊食宿等費用，一旦繳費後取消報名，已付的食宿等費用皆無法退款、轉讓。', ''],
        ['錄取信 > ② 食宿', 'approval.lodging.heading', '小標', '② 食宿登記　截止：6 月 20 日晚上 8 點前', ''],
        ['錄取信 > ② 食宿', 'approval.lodging.button', '按鈕', '前往食宿登記', ''],
        ['錄取信 > ② 食宿', 'approval.lodging.warning', '警示', '填寫緊急聯絡人、飲食、交通、證件等資料。本表單送出後僅能再修改 1 次（共計 2 次送出機會），請務必確認後再送出。', ''],
        ['錄取信 > ③ 快篩', 'approval.quicktest.heading', '小標', '③ 快篩檢測上傳　依各時段截止：', ''],
        ['錄取信 > ③ 快篩', 'approval.quicktest.button', '按鈕', '前往上傳快篩', ''],
        ['錄取信 > ③ 快篩', 'approval.quicktest.detail1', '段落', '・8/17 上午 8 點至晚上 8 點前　・8/19 上午 12 點前', ''],
        ['錄取信 > ③ 快篩', 'approval.quicktest.detail2', '段落', '（課程期間 8/20、8/22 快篩結果現場繳交，不需線上上傳）', ''],
        ['錄取信 > ③ 快篩', 'approval.quicktest.detail3', '段落', '檢測結果需載明日期、報名序號、姓名；快篩試劑請自備。', ''],
        ['錄取信 > ④ 承諾書', 'approval.pledge.heading', '小標', '④ 承諾書　現場繳交（不需線上送出）', ''],
        ['錄取信 > ④ 承諾書', 'approval.pledge.button', '按鈕', '下載承諾書 (Word)', ''],
        ['錄取信 > ④ 承諾書', 'approval.pledge.warning', '警示', '請下載列印並親筆簽名，於 8/19 報到當日交給現場法工。本文件不需線上送出，但未繳交承諾書恕無法入營。', ''],
        ['錄取信 > 費用方案表', 'approval.feePlan.heading', '小標', '費用方案', ''],
        ['錄取信 > 費用方案表', 'approval.feePlan.note', '說明', '8 種方案：A1/A2/B1/B2/C1/C2/D1/D2，其中 1=匯款、2=刷卡（金額 18,600 — 23,290）。詳見「繳費頁」工作表。', ''],
        ['錄取信 > 匯款帳號', 'approval.bank.heading', '段標', '匯款帳號（選擇匯款方案請使用）', ''],
        ['錄取信 > 匯款帳號', 'approval.bank.tw.label', '段落', '台灣法友', ''],
        ['錄取信 > 匯款帳號', 'approval.bank.tw.info', '段落', '戶名：台灣四念處學會 ／ 第一銀行 仁和分行（代號 007）／ 帳號：16510068750', ''],
        ['錄取信 > 匯款帳號', 'approval.bank.intl.label', '段落', '國外法友', ''],
        ['錄取信 > 匯款帳號', 'approval.bank.intl.info', '段落', '戶名：台灣四念處學會 ／ 第一銀行 仁和分行（代號 007）／ 帳號：16540016022', ''],
        ['錄取信 > 匯款帳號', 'approval.bank.warning', '警示', '匯款時請備註姓名與繳費碼：{繳費碼}，並於上方「前往繳費」頁面回填匯款後五碼。', '保留 {繳費碼}'],
        ['錄取信 > 三、住宿', 'approval.section3.item1', '列表', '房間皆為四人房，採單獨床位配置，附兩套衛浴。', ''],
        ['錄取信 > 三、住宿', 'approval.section3.item2', '列表', '如需安排兩人一間，請先私訊向主辦單位確認房間數量是否足夠；經確認後，每人需補差額新台幣 7,000 至 9,000 元。', ''],
        ['錄取信 > 四、報到', 'approval.section4.time', '段落', '時間：2026年8月19日上午10點（台北時間）', ''],
        ['錄取信 > 四、報到', 'approval.section4.venue', '段落', '場地：日月潭湖畔會館', ''],
        ['錄取信 > 四、報到', 'approval.section4.address', '段落', '地址：南投縣魚池鄉日月村中正路101號', ''],
        ['錄取信 > 五、課程', 'approval.section5.content', '段落', '2026年8月20日至8月24日，共5天', ''],
        ['錄取信 > 六、結束', 'approval.section6.content', '段落', '2026年8月24日下午5點30分（可選擇當日離營或25日上午9點30分前離營）', ''],
        ['錄取信 > 七、食宿', 'approval.section7.content', '段落', '請從本信第二段「② 前往食宿登記」連結進入填寫，截止時間為 6/20 晚上 8 點。本表單送出後僅能再修改 1 次（共計 2 次送出機會），請務必確認後再送出。', ''],
        ['錄取信 > 八、群組', 'approval.section8.content', '段落', '資料經確認無誤後，學會將以學員所提供之 LINE 或微信，邀請您加入 8 月禪修課程群組。', ''],
        ['錄取信 > 九、承諾事項', 'approval.section9.item1', '列表', '請遵從指導老師的課程安排指導及主辦方的規定。課程期間將全程進行拍攝與錄音，作為法佈施；學員需接受出鏡，並在課後不要求刪減個人互動的相關音視頻。', ''],
        ['錄取信 > 九、承諾事項', 'approval.section9.item2', '列表', '用餐時間，禁語。', ''],
        ['錄取信 > 九、承諾事項', 'approval.section9.item3', '列表', '請務必全程佩戴學員證。', ''],
        ['錄取信 > 九、承諾事項', 'approval.section9.item4', '列表', '課程期間請遵守作息時間，勿遲到早退，影響他人。', ''],
        ['錄取信 > 九、承諾事項', 'approval.section9.item5', '列表', '課程期間不可使用通訊軟體、手機。為示尊重，未獲得老師許可，上課中請勿拍照、攝影或錄音。', ''],
        ['錄取信 > 九、承諾事項', 'approval.section9.item6', '列表', '請輕聲細語，勿打擾他人禪修。', ''],
        ['錄取信 > 九、承諾事項', 'approval.section9.item7', '列表', '為護持禪眾修行與隱私保護，未經同意不得外傳任何資訊。', ''],
        ['錄取信 > 九、承諾事項', 'approval.section9.item8', '列表', '因故無法參加，請提早告知，俾利主辦方作業處理，恕無法退還已繳費用。', ''],
        ['錄取信 > 九、承諾事項', 'approval.section9.item9', '列表', '禪修期間，必須全程參加課程，勿遲到早退，私人事務請事先安排妥當。若課程開始當日無故不到，又未告知者，將影響下次報名資格。', ''],
        ['錄取信 > 九、承諾事項', 'approval.section9.item10', '列表', '主辦單位不提供禪修課程之外的其他服務，如：安排家屬住宿、安排旅遊、安排課程後的參學等。', ''],
        ['錄取信 > 九、承諾事項', 'approval.section9.item11', '列表', '除颱風、天災或不可抗拒之因素，禪修課程照常舉辦。', ''],
        ['錄取信 > 十、海外入境', 'approval.section10.content', '段落', '請進入中華民國移民署查詢：https://www.immigration.gov.tw/', ''],
        ['錄取信 > 十一、航班建議', 'approval.section11.a.heading', '小標', 'a. 來台抵達時間', ''],
        ['錄取信 > 十一、航班建議', 'approval.section11.a.item1', '列表', '建議抵達：8 月 19 日下午 2:00 至 2:30 以前（台北時間）。', ''],
        ['錄取信 > 十一、航班建議', 'approval.section11.a.item2', '列表', '集合地點：桃園國際機場（TPE）第一航廈，完成入境並領取行李後，請至出關後右側服務台前集合。', ''],
        ['錄取信 > 十一、航班建議', 'approval.section11.a.item3', '列表', '行程安排：現場將由法工人員接機，並統一搭乘專車前往日月潭湖畔會館。', ''],
        ['錄取信 > 十一、航班建議', 'approval.section11.b.heading', '小標', 'b. 離台時間', ''],
        ['錄取信 > 十一、航班建議', 'approval.section11.b.item1', '列表', '專車出發：8 月 25 日上午 9:00（台北時間）自會館準時發車。', ''],
        ['錄取信 > 十一、航班建議', 'approval.section11.b.item2', '列表', '預計抵達：預計於下午 2:00 至 3:00 抵達桃園國際機場第一航廈。', ''],
        ['錄取信 > 十二、', 'approval.section12.content', '段落', '如有任何爭議，台灣四念處學會將保留最終決定權。', ''],
        ['錄取信 > 繳費碼', 'approval.codebox.label', '小標', '您的專屬繳費碼', ''],
        ['錄取信 > 繳費碼', 'approval.codebox.note', '段落', '查詢報名狀態時需使用此碼', ''],
        ['錄取信 > 學員專區', 'approval.highlight.title', '小標', '📋 學員專區', ''],
        ['錄取信 > 學員專區', 'approval.highlight.intro', '段落', '點擊下方連結直接進入您的學員專區，查看繳費、食宿登記與快篩上傳進度：', ''],
        ['錄取信 > 學員專區', 'approval.highlight.button', '按鈕', '進入學員專區', ''],
        ['錄取信 > 簽尾', 'approval.signoff.line1', '段落', '如有任何問題，請聯繫台灣四念處學會。', ''],
        ['錄取信 > 簽尾', 'approval.signoff.line2', '段落', '台灣四念處學會 合十', ''],
      ],
    },

    // ============== Email：互動報名邀請信 ==============
    {
      key: 'email-interactive-invite',
      title: 'Email-互動報名邀請信',
      rows: [
        ['互動邀請信 > 主旨', 'invite.subject', '主旨', '【第二屆台灣四念處禪修】互動報名開放通知', ''],
        ['互動邀請信 > 表頭', 'invite.h1', '主標', '第二屆台灣四念處禪修課程－互動報名開放通知', ''],
        ['互動邀請信 > 開場', 'invite.greeting', '段落', '{姓名} 法友您好：', '保留 {姓名}'],
        ['互動邀請信 > 開場', 'invite.intro', '段落', '本屆禪修課程的「互動報名」已開放填寫，請於截止前完成登記。', ''],
        ['互動邀請信 > 規則', 'invite.section.heading', '段標', '關於互動報名', ''],
        ['互動邀請信 > 規則', 'invite.section.intro', '段落', '互動報名分為兩部分：集體互動與分組互動，請在同一表單內一併登記。', ''],
        ['互動邀請信 > 規則', 'invite.section.item1', '列表', '集體互動：勾選想參加的場次（可複選）。學會將以隨機抽籤決定中簽名單。', ''],
        ['互動邀請信 > 規則', 'invite.section.item2', '列表', '分組互動：將四位老師依意願順序排序（1～4）。學會將依意願順序與容量分配。', ''],
        ['互動邀請信 > 規則', 'invite.section.item3', '列表', '兩部分皆非必填，可只報其一或皆不報；若皆不報亦請送出空表單以結束流程。', ''],
        ['互動邀請信 > 規則', 'invite.section.item4', '列表', '抽籤結果由學會於截止後另行寄信通知；中簽者再依信內連結填寫互動作業。', ''],
        ['互動邀請信 > 按鈕', 'invite.button', '按鈕', '前往填寫互動報名', ''],
        ['互動邀請信 > 警示', 'invite.warning', '警示', '請於截止時間前完成填寫；逾時系統將不再收件。表單可重複修改、以最後一次送出為準。', ''],
      ],
    },

    // ============== Email：互動結果通知信 ==============
    {
      key: 'email-interactive-notify',
      title: 'Email-互動結果通知信',
      rows: [
        ['互動結果信 > 主旨', 'notify.subject', '主旨', '【第二屆台灣四念處禪修】互動報名結果通知', ''],
        ['互動結果信 > 表頭(中簽)', 'notify.h1.won', '主標', '互動報名結果通知 🎉', ''],
        ['互動結果信 > 表頭(沒中)', 'notify.h1.notwon', '主標', '互動報名結果通知', ''],
        ['互動結果信 > 開場', 'notify.greeting', '段落', '{姓名} 法友您好：', '保留 {姓名}'],
        ['互動結果信 > 開場', 'notify.intro', '段落', '您於互動報名的抽籤結果如下：', ''],
        ['互動結果信 > 集體中簽', 'notify.group.won', '段落', '✓ 集體互動：中簽 (序號 {序號})', '保留 {序號}'],
        ['互動結果信 > 集體中簽', 'notify.group.session', '段落', '場次：{日期}（{星期}）{時間}　{老師}', '保留 {日期}{星期}{時間}{老師}'],
        ['互動結果信 > 集體未中', 'notify.group.lost', '段落', '✗ 集體互動：未中簽', ''],
        ['互動結果信 > 分組中簽', 'notify.small.won', '段落', '✓ 分組互動：中簽 (序號 {序號})', '保留 {序號}'],
        ['互動結果信 > 分組中簽', 'notify.small.group', '段落', '小組：{老師} 組　日期：{日期}', '保留 {老師}{日期}'],
        ['互動結果信 > 分組未中', 'notify.small.lost', '段落', '✗ 分組互動：未中簽', ''],
        ['互動結果信 > 中簽下一步', 'notify.task.heading', '段標', '下一步：填寫互動作業', '只有中簽者會看到'],
        ['互動結果信 > 中簽下一步', 'notify.task.intro', '段落', '恭喜您中簽！請於課程開始前填寫互動作業，老師會依您的問題與背景準備指導。', ''],
        ['互動結果信 > 中簽下一步', 'notify.task.button', '按鈕', '前往填寫互動作業', ''],
        ['互動結果信 > 中簽下一步', 'notify.task.detail', '段落', '作業內容包含：基本背景、近期實修狀況、希望老師指導的問題（每題 75 字內）。', ''],
        ['互動結果信 > 沒中簽鼓勵', 'notify.alert.notwon', '警示', '本次互動名額有限，未能中簽請勿介懷。期望未來有更多機緣與老師互動。', '只有沒中簽者會看到'],
      ],
    },

    // ============== Email：正式學員通知信 ==============
    {
      key: 'email-formal',
      title: 'Email-正式學員通知信',
      rows: [
        ['正式通知信 > 主旨', 'formal.subject', '主旨', '【第二屆台灣四念處禪修】正式學員通知', ''],
        ['正式通知信 > 表頭', 'formal.h1', '主標', '正式學員通知', ''],
        ['正式通知信 > 開場', 'formal.greeting', '段落', '{姓名} 法友您好：', '保留 {姓名}'],
        ['正式通知信 > 開場', 'formal.intro', '段落', '您已完成報名與食宿登記所有流程。以下為我們收到的完整資料，請您再次核對，若有誤請即刻聯絡學會：', ''],
        ['正式通知信 > 一、學員資料', 'formal.section1.heading', '段標', '一、學員資料', ''],
        ['正式通知信 > 一、學員資料', 'formal.section1.note', '說明', '此段顯示報名時填的資料：學號、中文姓名、護照英文姓名、性別、法名、居住地、電話、Email、繳費方案、繳費狀態。', ''],
        ['正式通知信 > 二、食宿', 'formal.section2.heading', '段標', '二、食宿登記', ''],
        ['正式通知信 > 二、食宿', 'formal.section2.note', '說明', '此段顯示食宿登記資料：入住/離開日、前往離開方式、飲食、過午不食、茶點、晚餐、打鼾、緊急聯絡人、航班。', ''],
        ['正式通知信 > 三、證件', 'formal.section3.heading', '段標', '三、證件檢核', ''],
        ['正式通知信 > 三、證件', 'formal.section3.note', '說明', '此段顯示文件上傳狀態：個人相片、身分證/護照/ARC、機票、快篩。', ''],
        ['正式通知信 > 四、注意事項', 'formal.section4.heading', '段標', '四、課程注意事項', ''],
        ['正式通知信 > 四、注意事項', 'formal.section4.item1', '列表', '課程期間 8/20、8/22 快篩結果現場繳交，不需線上上傳。', ''],
        ['正式通知信 > 四、注意事項', 'formal.section4.item2', '列表', '入住日月潭湖畔會館辦理入住時間：下午 3 點後；請攜帶身分證+健保卡（國內）或護照正本（國外）；自備雨具、盥洗用具、衣架。', ''],
        ['正式通知信 > 四、注意事項', 'formal.section4.item3', '列表', '課程全程配戴口罩、禁用手機、用餐禁語、全程佩戴學員證、未經同意禁止拍照錄影錄音。', ''],
        ['正式通知信 > 四、注意事項', 'formal.section4.item4', '列表', '若感冒確診須取消課程；若課程期間陽性，同寢室 4 人需房內隔離並改 ZOOM 上課。', ''],
        ['正式通知信 > 簽尾', 'formal.footer', '段落', '若資料有誤請儘速聯絡學會。', ''],
      ],
    },

    // ============== Email：快篩確認信 ==============
    {
      key: 'email-quicktests',
      title: 'Email-快篩確認信',
      rows: [
        ['快篩信 > 主旨', 'quicktests.subject', '主旨', '【第二屆台灣四念處禪修】快篩檢測上傳確認', ''],
        ['快篩信 > 表頭', 'quicktests.h1', '主標', '快篩上傳已收到 🙏', ''],
        ['快篩信 > 開場', 'quicktests.greeting', '段落', '{姓名} 法友您好，', '保留 {姓名}'],
        ['快篩信 > 開場', 'quicktests.intro', '段落', '系統已收到您的快篩檢測結果上傳，目前狀態如下：', ''],
        ['快篩信 > 警示', 'quicktests.warning', '警示', '尚未上傳的時段請於規定時間前上傳，否則將影響入營或同寢隔離安排。', ''],
        ['快篩信 > 段落', 'quicktests.note', '段落', '如需重新上傳或補上其他時段，可隨時回到上傳頁。', ''],
        ['快篩信 > 按鈕', 'quicktests.button', '按鈕', '前往上傳快篩檢測結果', ''],
        ['快篩信 > 詳情', 'quicktests.detail.intro', '段落', '請依下列時間上傳檢測結果（檢測結果需載明日期、報名序號、姓名；快篩試劑請自備）：', ''],
        ['快篩信 > 詳情', 'quicktests.detail.1', '段落', '・8/17 上午 8:00 至晚上 8:00 前', ''],
        ['快篩信 > 詳情', 'quicktests.detail.2', '段落', '・8/19 上午 12:00 前', ''],
        ['快篩信 > 詳情', 'quicktests.detail.3', '段落', '（課程期間 8/20、8/22 快篩結果現場繳交，不需線上上傳）', ''],
      ],
    },

    // ============== Email：食宿存檔信 ==============
    {
      key: 'email-archive',
      title: 'Email-食宿確認信',
      rows: [
        ['食宿信 > 主旨', 'archive.subject', '主旨', '【第二屆台灣四念處禪修】食宿登記確認', ''],
        ['食宿信 > 表頭', 'archive.h1', '主標', '食宿登記確認 🙏', ''],
        ['食宿信 > 開場', 'archive.greeting', '段落', '{姓名} 法友您好，', '保留 {姓名}'],
        ['食宿信 > 開場', 'archive.intro', '段落', '我們已收到您的食宿登記，以下是您目前選擇的方案與繳費資訊：', ''],
        ['食宿信 > 一、繳費資訊', 'archive.section1.heading', '段標', '繳費資訊', ''],
        ['食宿信 > 一、繳費資訊', 'archive.section1.note', '說明', '此段顯示報名時填的資料：繳費碼、中文姓名、報名序號、選擇方案、金額、繳費方式、繳費狀態、繳費備註、確認時間。', ''],
        ['食宿信 > 二、食宿登記資料', 'archive.section2.heading', '段標', '食宿登記資料', ''],
        ['食宿信 > 二、食宿登記資料', 'archive.section2.note', '說明', '此段顯示食宿登記資料：入住/離開、前往/離開方式、飲食、茶點、晚餐、打鼾、緊急聯絡人。', ''],
        ['食宿信 > 簽尾', 'archive.footer', '段落', '如您對方案或繳費資訊有疑問，請聯繫台灣四念處學會。', ''],
      ],
    },

    // ============== 系統通用：簽尾 / Footer ==============
    {
      key: 'common',
      title: '通用-Email簽尾與頁尾',
      rows: [
        ['Email 簽尾', 'common.email.signoff.line1', '段落', '如有任何問題，請聯繫台灣四念處學會。', '所有 email 共用'],
        ['Email 簽尾', 'common.email.signoff.line2', '段落', '台灣四念處學會 合十', '所有 email 共用'],
        ['Email 頁尾', 'common.email.copyright', '段落', '© 2026 台灣四念處禪修學會　All rights reserved.', '所有 email 共用'],
        ['網站頁尾', 'common.web.copyright', '段落', '© 2026 台灣四念處禪修學會　All rights reserved.', '所有頁面共用'],
        ['網站頁尾', 'common.web.email', '連結', 'satipatthana.tw@gmail.com', '所有頁面共用'],
        ['網站頁尾', 'common.web.org_full', '段落', '台灣四念處禪修學會', ''],
      ],
    },
  ],
}
